//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthIservices.OtherResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthIservices.OtherResourses.MessagesEn", typeof(MessagesEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved.
        /// </summary>
        public static string _001 {
            get {
                return ResourceManager.GetString("001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in saving.
        /// </summary>
        public static string _002 {
            get {
                return ResourceManager.GetString("002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data loading success.
        /// </summary>
        public static string _003 {
            get {
                return ResourceManager.GetString("003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data loading failed.
        /// </summary>
        public static string _004 {
            get {
                return ResourceManager.GetString("004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success.
        /// </summary>
        public static string _005 {
            get {
                return ResourceManager.GetString("005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password invalid.
        /// </summary>
        public static string _006 {
            get {
                return ResourceManager.GetString("006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save budget withot details.
        /// </summary>
        public static string _007 {
            get {
                return ResourceManager.GetString("007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete success.
        /// </summary>
        public static string _008 {
            get {
                return ResourceManager.GetString("008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        public static string _009 {
            get {
                return ResourceManager.GetString("009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master data loading success.
        /// </summary>
        public static string _010 {
            get {
                return ResourceManager.GetString("010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master data load failed.
        /// </summary>
        public static string _011 {
            get {
                return ResourceManager.GetString("011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired Please Login.
        /// </summary>
        public static string _012 {
            get {
                return ResourceManager.GetString("012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot verify Email.
        /// </summary>
        public static string _013 {
            get {
                return ResourceManager.GetString("013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found.
        /// </summary>
        public static string _014 {
            get {
                return ResourceManager.GetString("014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset email sent.Please check inbox..
        /// </summary>
        public static string _015 {
            get {
                return ResourceManager.GetString("015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed password reset.Please check email..
        /// </summary>
        public static string _016 {
            get {
                return ResourceManager.GetString("016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request processed success.
        /// </summary>
        public static string _017 {
            get {
                return ResourceManager.GetString("017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request process failed.
        /// </summary>
        public static string _018 {
            get {
                return ResourceManager.GetString("018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SucessFully Deleted.
        /// </summary>
        public static string _019 {
            get {
                return ResourceManager.GetString("019", resourceCulture);
            }
        }
    }
}
